/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB3;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class QLSV extends javax.swing.JFrame {
    ArrayList<Student> list = new ArrayList<>();  
    //Add danh sách vào bảng
    public void addStudent()
    {
        Student arr = new Student();
        
        arr.setHoten(txtHoten.getText());
        arr.setDiem(Double.parseDouble(txtDiem.getText()));
        arr.setNganh((String)cboNganh.getSelectedItem());
        
        list.add(arr);
        txtHocluc.setText(arr.getGrade());
        chkBonus.setSelected(arr.isBonus());
        
    }
    public void fillToTalbe()
    {
        DefaultTableModel model = (DefaultTableModel)tblSinhvien.getModel();
        model.setRowCount(0);
        
        for(Student arr : list)
        {
            Object[] row = new Object[]{arr.getHoten(),arr.getDiem(),arr.getNganh(),arr.getGrade(),arr.isBonus()};
            model.addRow(row);
        }
    }
    int index = 0;
    //Hiện lên các control
    public void showDeital()
    {
        index = tblSinhvien.getSelectedRow();
        
        Student sv = list.get(index);
        
        txtHoten.setText(""+ sv.getHoten());
        txtDiem.setText(""+ sv.getDiem());
        cboNganh.setSelectedIndex(index);
        txtHocluc.setText(sv.getGrade());
        chkBonus.setSelected(sv.isBonus());
    }
    //Xóa Danh sách trong table
    public void Remove()
    {
        list.remove(index);
        index = -1;
        txtHoten.setText("");
        txtDiem.setText("");
        txtHocluc.setText("");
        cboNganh.setSelectedIndex(0);
    }
    
    //Sắp xếp theo Tên
   
    public void oderByHoten()
    {
        //Comparator: Cung cấp các phương thức static để sắp xếp các phần tử của collection.
        Comparator<Student> com = new Comparator<Student>()
        {
            @Override
            public int compare(Student o1, Student o2)//Đặt tên Của danh sách Student
            {
                return o1.getHoten().compareTo(o2.getHoten());//Trả về lại dữ liệu tên danh sách
            }
        };
        Collections.sort(list,com);                 //Sắp xếp các phần tử String của list theo thứ tự tăng dần  
    }
    
    //Sắp xếp theo điểm
    public void oderByDiem()
    {
        //Comparator: Cung cấp các phương thức static để sắp xếp các phần tử của collection.
        Comparator<Student> com = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                Double d1 = o1.getDiem();           //o1.getDiem(): Lấy giá trị của o1 and Tạo giá trị Double cho d1
                Double d2 = o2.getDiem();           //o2.getDiem(): Lấy giá trị của o2 and Tạo giá trị Double cho d2
                return d1.compareTo(d2);  //Trả về d1 để so sánh các chuỗi cho trước, với chuỗi d2 theo thứ tự từ điển.
            }
        };
        Collections.sort(list,com);                 //Sắp xếp các phần tử Double của list theo thứ tự tăng dần 
    }
    
    
    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboNganh = new javax.swing.JComboBox<>();
        chkBonus = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtHocluc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhvien = new javax.swing.JTable();
        bttAdd = new javax.swing.JButton();
        bttReset = new javax.swing.JButton();
        bttUpdate = new javax.swing.JButton();
        bttRemove = new javax.swing.JButton();
        bttSapxeptheodiem = new javax.swing.JButton();
        bttSapxeptheoten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Điểm");

        jLabel4.setText("Học lực");

        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Thiết kế trang web", "Phát triển phần mềm", "Ứng dụng phần mềm", "Marketing", "Quản lý khách sạn" }));

        chkBonus.setText("Có phần thưởng hay không?");

        jLabel5.setText("Ngành");

        txtHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenActionPerformed(evt);
            }
        });

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });

        tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ Tên", "Điểm", "Ngành", "Học lực", "Phần Thưởng"
            }
        ));
        tblSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhvien);

        bttAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Actions-document-new-icon.png"))); // NOI18N
        bttAdd.setText("Add");
        bttAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddActionPerformed(evt);
            }
        });

        bttReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Action-file-new-icon.png"))); // NOI18N
        bttReset.setText("Reset");
        bttReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttResetActionPerformed(evt);
            }
        });

        bttUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Actions-document-edit-icon.png"))); // NOI18N
        bttUpdate.setText("Update");
        bttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUpdateActionPerformed(evt);
            }
        });

        bttRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Action-cancel-icon.png"))); // NOI18N
        bttRemove.setText("Remove");
        bttRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRemoveActionPerformed(evt);
            }
        });

        bttSapxeptheodiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Actions-view-refresh-icon.png"))); // NOI18N
        bttSapxeptheodiem.setText("Sắp xếp theo điểm");
        bttSapxeptheodiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSapxeptheodiemActionPerformed(evt);
            }
        });

        bttSapxeptheoten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB3/Action-reload-icon.png"))); // NOI18N
        bttSapxeptheoten.setText("Sắp xếp theo tên");
        bttSapxeptheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSapxeptheotenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoten))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(93, 93, 93))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBonus)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bttAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bttReset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bttUpdate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bttRemove))
                                            .addComponent(txtHocluc, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))))
                                .addGap(27, 166, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(bttSapxeptheodiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(bttSapxeptheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtHoten))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSapxeptheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSapxeptheodiem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemActionPerformed

    private void bttRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRemoveActionPerformed
        // TODO add your handling code here:
        Remove();
        fillToTalbe();
        JOptionPane.showMessageDialog(this, "Remove thành công");
    }//GEN-LAST:event_bttRemoveActionPerformed

    private void txtHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenActionPerformed

    private void bttAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddActionPerformed
        // TODO add your handling code here:
        addStudent();
        fillToTalbe();
        if((txtHoten.getText().equals("")) && (txtDiem.getText().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống","Error",JOptionPane.WARNING_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Add thành công");
        }
    }//GEN-LAST:event_bttAddActionPerformed

    private void bttResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttResetActionPerformed
        // TODO add your handling code here:
        txtHoten.setText("");
        txtDiem.setText("");
        txtHocluc.setText("");
        cboNganh.setSelectedIndex(0);
        
        txtHoten.requestFocus();
    }//GEN-LAST:event_bttResetActionPerformed

    private void tblSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhvienMouseClicked
        // TODO add your handling code here:
        showDeital();
    }//GEN-LAST:event_tblSinhvienMouseClicked

    private void bttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUpdateActionPerformed
        // TODO add your handling code here:
        Student arr = list.get(index);
        
        arr.setHoten(txtHoten.getText());
        arr.setDiem(Double.parseDouble(txtDiem.getText()));
        arr.setNganh((String)cboNganh.getSelectedItem());
        
        fillToTalbe();
        JOptionPane.showMessageDialog(this, "Update Thông Tin thành công");
    }//GEN-LAST:event_bttUpdateActionPerformed

    private void bttSapxeptheodiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSapxeptheodiemActionPerformed
        // TODO add your handling code here:
        oderByDiem();
        fillToTalbe();
    }//GEN-LAST:event_bttSapxeptheodiemActionPerformed

    private void bttSapxeptheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSapxeptheotenActionPerformed
        // TODO add your handling code here:
        oderByHoten();
        fillToTalbe();
    }//GEN-LAST:event_bttSapxeptheotenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAdd;
    private javax.swing.JButton bttRemove;
    private javax.swing.JButton bttReset;
    private javax.swing.JButton bttSapxeptheodiem;
    private javax.swing.JButton bttSapxeptheoten;
    private javax.swing.JButton bttUpdate;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JCheckBox chkBonus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhvien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHocluc;
    private javax.swing.JTextField txtHoten;
    // End of variables declaration//GEN-END:variables
}
